#!/usr/bin/env python3
"""Build docs/quiz/quiz-bank.js from the Markdown quiz banks.

Sources (same question format in both files):
  practice/quizzes/README.md          — course quizzes A–D (Part 1) + practice questions N1–N58 (Part 2)
  practice/quizzes/extra-questions.md — original questions X1–X40

    python3 tools/build_quiz_bank.py
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import forge_md  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
REPO = "https://github.com/Normansrule/algorithm-forge/blob/main/"
SOURCES = ["practice/quizzes/README.md", "practice/quizzes/extra-questions.md"]
# Part 1 of the README is organized by topic; map each topic section to its chapter.
PART1_CHAPTER = {"1.1": 1, "1.2": 2, "1.3": 2, "1.4": 2, "1.5": 2, "1.6": 3, "1.7": 3, "1.8": 4}
CHAPTERS = {1: "Introduction", 2: "Analysis Framework", 3: "Brute Force & Exhaustive Search", 4: "Decrease-and-Conquer",
            5: "Divide-and-Conquer", 6: "Transform-and-Conquer", 7: "Space-Time Tradeoffs", 8: "Dynamic Programming",
            9: "Greedy Technique", 10: "Iterative Improvement", 11: "Limitations of Algorithm Power", 12: "Coping with Limitations"}

forge_md.LINK_REWRITE[:] = [
    (r"^\.\./\.\./", REPO),
    (r"^\.\./", REPO + "practice/"),
    (r"^([\w-]+\.md)(#.*)?$", REPO + r"practice/quizzes/\1\2"),
]

Q_START = re.compile(r"^\*\*(Q\d+\.\d+|N\d+|X\d+)(?:\s*\(([^)]*)\))?\.\*\*\s*(.*)$")
OPTION = re.compile(r"^- ([a-h])\)\s+(.*)$")


def parse(path):
    lines = open(os.path.join(ROOT, path), encoding="utf-8").read().split("\n")
    out, chapter, i = [], None, 0
    while i < len(lines):
        ln = lines[i]
        m = re.match(r"^## (1\.\d)\s", ln)
        if m:
            chapter = PART1_CHAPTER.get(m.group(1), chapter)
        m = re.match(r"^## Chapter (\d+)", ln)
        if m:
            chapter = int(m.group(1))
        m = Q_START.match(ln)
        if not m:
            i += 1
            continue
        qid, tag, first = m.group(1), m.group(2), m.group(3)
        q_lines = [first]
        i += 1
        while i < len(lines) and not OPTION.match(lines[i]):
            q_lines.append(lines[i])
            i += 1
        options = []
        while i < len(lines) and (OPTION.match(lines[i]) or not lines[i].strip()):
            om = OPTION.match(lines[i])
            if om:
                options.append(om.group(2).strip())
            i += 1
            if i < len(lines) and lines[i].startswith("<details"):
                break
        assert lines[i].startswith("<details"), f"{path}: {qid} has no <details> block"
        i += 1
        det = []
        while not lines[i].startswith("</details>"):
            det.append(lines[i])
            i += 1
        i += 1
        det_md = "\n".join(det).strip()
        am = re.search(r"\*\*Answer:\s*([a-h])\)(.*?)\*\*", det_md)
        assert am, f"{qid}: no answer line"
        answer = "abcdefgh".index(am.group(1))
        explain_md = (det_md[:am.start()] + det_md[am.end():]).strip()
        verdict = am.group(2).strip().rstrip(".")
        src = ("Course quiz" + (f" · {tag}" if tag else "")) if qid.startswith("Q") else ("Forge practice" if qid.startswith("N") else "Forge original")
        out.append({
            "id": qid, "ch": chapter, "src": src, "course": qid.startswith("Q"),
            # statement lists like "I. …", "II. …", "A. …" become bullet lines
            "q": forge_md.render("\n".join(("- " + l) if re.match(r"^(I{1,3}|IV|[A-D])\.\s", l) else l for l in q_lines).strip()),
            "options": [forge_md.inline(o) for o in options],
            "answer": answer,
            "verdict": forge_md.inline(verdict) if verdict else "",
            "explain": forge_md.render(explain_md),
        })
    return out


def main():
    qs = []
    for s in SOURCES:
        qs += parse(s)
    ids = [q["id"] for q in qs]
    assert len(ids) == len(set(ids)), "duplicate question ids"
    for q in qs:
        assert q["ch"] in CHAPTERS, (q["id"], q["ch"])
        assert 2 <= len(q["options"]) and q["answer"] < len(q["options"]), q["id"]
        blob = q["q"] + "".join(q["options"]) + q["explain"]
        assert "$" not in re.sub(r"<code>.*?</code>", "", blob), f"unconverted math in {q['id']}"
    data = {"chapters": CHAPTERS, "questions": qs}
    js = ("/* GENERATED by tools/build_quiz_bank.py from practice/quizzes/README.md and practice/quizzes/extra-questions.md.\n"
          "   Edit the Markdown, then rebuild. */\n"
          "window.FORGE_QUIZ = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n")
    os.makedirs(os.path.join(ROOT, "docs", "quiz"), exist_ok=True)
    path = os.path.join(ROOT, "docs", "quiz", "quiz-bank.js")
    open(path, "w", encoding="utf-8").write(js)
    by = {}
    for q in qs:
        by[q["ch"]] = by.get(q["ch"], 0) + 1
    print(f"wrote {os.path.relpath(path, ROOT)}: {len(qs)} questions", dict(sorted(by.items())),
          f"course={sum(q['course'] for q in qs)}")


if __name__ == "__main__":
    main()
